controller_configuration:
  reset:
    button_index: 6
  gripper:
    button_inc_index: 3
    button_dec_index: 2
  move_tool_center:
    button_index: 5
  reset_tool_center: 
    button_index: 4
  hold_pose:
    axis_index: 7
  
