reset_button_idx: 6
controller_configuration:
  translate_x:
    scale: 0.5
    axis_inc_index: 5
    axis_dec_index: 2 
  translate_y:
    axis_index: 0
    scale: -1.0
  translate_z:
    axis_index: 1
    scale: -1.0
  rotate_roll:
    axis_index: 3
    scale: 2.0
  rotate_pitch:
    axis_index: 4
  rotate_yaw:
    button_inc_index: 1
    button_dec_index: 0
  gripper:
    button_inc_index: 5
    button_dec_index: 4
  